### ISSUE TITLE
Unhandled Exception: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by Mhero7** [Ekey/MBTL.BIN.Tool#13]
Hello, I cannot extract any BIN files and im getting the following Error's. Did I do anything wrong?

<img width="1728" alt="Screenshot 2023-01-13 at 12 04 19" src="https://user-images.githubusercontent.com/111390450/212305832-4a6c3d56-7947-4457-8138-214845a28242.png">

I'm using ARM Windows 11 via Parallels Desktop on my Macbook perhaps this is the reason.

**Comment by Ekey** [comment]
What arguments do you use? Must be like this in your case:

MBTL.Unpacker.exe "**C:\Games\Melty Blood - Type Lumina**" "**C:\Unpacked**"

You can specify a directory for unpacked files instead of **C:\Unpacked**

Also make sure the game has the [latest update](https://steamdb.info/depot/1372281/history/?changeid=M:5508480822591740530)

**Comment by Mhero7** [comment]
thanks this worked! I was inputing a specific bin file that's the issue.
